### ISSUE TITLE
Full disclosure on git-gpg weaknesses

### ISSUE THREAD

**Issue by pfalcon** [rustyio/git-gpg#1]
I very much appreciate git-gpg README, where survey and criticism of other git encryption solutions is provided. It lacks only one thing - providing truthful discussion of git-gpg's own weaknesses. That makes git-gpg look like the ultimate solution, which it of course isn't. And the main issue is that git-gpg isn't compatible with ... git! That's because instead of using git protocols (or access schemes, speaking widely), it uses rsync. But git server doesn't offer rsync protocol! And no git service, no sysadmin will let you access git repositories with a standalone rsync service (that doesn't make sense and is a security risk). And if you're your own sysadmin, then there're so many ways to solve git encryption problem, that git-gpg is unlikely the brightest of them.

And that's how all the other software you quote differs from git-gpg - good or bad, it allows to work transparently with existing git infrastructure, unlike yours.

So, again, if you like to entertain readers with Hoar quotes when criticizing other software, maybe you'd also want to provide some reflection about your own solution ;-). Or maybe not, up to you.

**Comment by rustyio** [comment]
Fair points. git-gpg isn't perfect. Like anything, it has trade-offs.

In this case, git-gpg fits my needs better than other solutions. Specifically, I needed a way to synchronize private files between trusted endpoints under my control, through an untrusted cloud server _not_ under my control. git-gpg chooses tradeoffs that are acceptable for that use case. It sounds like you have different needs.

To address your points individually:
1. **git-gpg isn't compatible with git.** - True. But once the content is encrypted, it looks like a bunch of binary blobs, so git can't do anything smart with it anyway.
2. **git-gpg doesn't use git as a transport mechanism.** True. But it uses rsync-over-ssh, which is a more common transport method than git. Honestly, I didn't think too much about the transport mechanism (or, referring back to the previous concern, the storage system). I chose the simplest thing that worked. A motivated developer could extend git-gpg to use git as the transport protocol and storage mechanism, and it should work just fine. I personally think it adds unnecessary complexity.
3. **No sysadmin will let you access git repositories with a standalone rsync server.** - I'm definitely not advocating that you run an rsync service. As you point out, it is not secure. rsync automatically uses ssh when available. Perhaps I should have mentioned this in the docs, but in my mind it's fairly widespread knowledge.
4. **If you're your own sysadmin, [there are better ways to] solve the git encryption problem.** - I disagree, and would love to hear your suggestions. I'll happily switch to a better solution, it means less code to maintain.

Thank you for your thoughtful comments, I think others will find value in this discussion, and I've updated the README to describe git-gpg's tradeoffs.
