### ISSUE TITLE
how does git gpg handle large-file encryption (like git-LFS)?

### ISSUE THREAD

**Issue by tencherry10** [rustyio/git-gpg#4]
git gpg's approach is git encryption is interesting, but your doc doesn't make clear how it handles large files via things like git-lfs. Does git gpg have a story/approach with respect to git LFS files?

**Comment by rustyio** [comment]
git-gpg has not been tested with git-lfs. Its intended use is to secure sensitive code and configuration files. Sounds like this might not be the right tool for your needs. Sorry about that!
